baseurl = "https://www.example.com/"
title = "RAELLEN"
author = "Raellen"
canonifyurls = true
languagecode = "en"
theme = "axiom"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Black & Light"
  disableWebFonts = false

[[menu.main]]
    name = "Archive"
    url  = "/archive/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url  = "tags"
    weight = 2
[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 3